### PR TITLE
Fix cross-file test isolation and nondeterministic CI failures

### PR DESCRIPTION
**Pull request by devxoul**
## Summary

Fixes 20 pre-existing CI test failures on `main` that only surface when the full `bun test src/` suite runs — each test passes in isolation. These failures are independent of any feature work; re-running `main`'s own CI reproduces the identical 20 failures.

The root causes are two distinct isolation bugs: process-global module-mock leakage from Bun's `mock.module()` API, and non-deterministic directory ordering from `readdirSync`.

### 1. Process-global module-mock leakage

Bun runs all test files in a single process, in alphabetical order. `mock.module(...)` is process-global and persists across files unless explicitly restored.

Several Webex and Instagram command test files called `mock.module(...)` without cleanup:

- Webex tests (member, message, snapshot, space) mock the `../client` module with a stub `WebexClient` that lacks `testAuth`. This stub leaked into `webex/commands/auth.test.ts` on later runs, breaking it with `TypeError: ...testAuth is not a function`.
- Instagram tests (auth, chat, message) mock the `./shared` and `../credential-manager` modules. These leaked into later Instagram command tests and broke their auth-error and missing-token assertions.

Fix: add `afterAll(() => mock.restore())` to each offending file so module mocks are cleaned up per file.

### 2. Non-deterministic directory order

`discoverBrowserProfileDirs` in `src/shared/chromium/browsers.ts` iterated `readdirSync` entries in raw filesystem order, which is platform-dependent. On the CI runner, this caused "Profile 1" to be dropped from the expected sequence.

Fix: sort entries by name before processing so the result is deterministic across filesystems.

### `src/shared/chromium/browsers.ts`

Sort `readdirSync` entries by name before constructing profile paths. Pure determinism fix; no behavior change on filesystems that already return sorted entries.

### Webex command tests (4 files)

`src/platforms/webex/commands/{member,message,snapshot,space}.test.ts` — add `afterAll(() => mock.restore())` to clean up the `../client` module mock after each file, preventing the stub `WebexClient` from leaking into `auth.test.ts`.

### Instagram command tests (3 files)

`src/platforms/instagram/commands/{auth,chat,message}.test.ts` — add `afterAll(() => mock.restore())` to clean up the `./shared` and `../credential-manager` module mocks after each file, preventing them from breaking auth-error and missing-token assertions in downstream test files.

## Testing

- `bun typecheck` — clean.
- `bun lint` — 0 warnings / 0 errors.
- `bunx oxfmt --check` on all changed files — clean.
- `bun test src/shared/` — 104 pass / 0 fail (browsers determinism fix confirmed).
- Webex polluter files + `auth.test.ts` run together — `testAuth` leak gone, all pass.
- Instagram command group — 38 pass / 0 fail.

Note: a full `bun run test` cannot complete in some environments because a handful of webex/instagram/teams tests perform real network or device-grant auth and hang without network access. This PR does not change that behavior — the fixes target only the isolation and determinism bugs that fail deterministically in CI.

---
## Summary by cubic
Fixes cross-file test isolation and nondeterministic CI failures. Replaces global mocks with scoped spies, adds a global test preload to auto-restore, sorts Chromium profiles deterministically, and makes command tests halt on process.exit. Eliminates 20 flaky failures in `bun test src/`.

- **Bug Fixes**
  - Webex tests: use `spyOn(WebexClient.prototype, 'login')` and a scoped `spyOn(errorHandler, 'handleError')`; `whoami.test.ts` now drives the unauthenticated path via the login spy and keeps `testAuth` intact.
  - Instagram tests: replace `mock.module('./shared')` and `mock.module('../credential-manager')` with spies on `withInstagramClient` and `InstagramCredentialManager.prototype` methods; restore spies in `afterEach`.
  - Discord and Webex command tests: mock `process.exit` to throw a `ProcessExit` sentinel so control flow stops; assert JSON error output and `exit(1)`. Discord tests now restore the `process.exit` spy in `finally` to avoid relying on the preload.
  - Add global preload `src/test-setup.ts` that runs `mock.restore()` after each test; wired via `bunfig.toml` and excluded from `tsconfig.json` build.
  - `discoverBrowserProfileDirs`: sort `readdirSync` entries by name for stable profile ordering.

- **Docs**
  - No SKILL.md or docs changes needed.

<sup>Written for commit 6207ca6bbcb8999c30f71ea11237e41c20a14f08. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/agent-messenger/agent-messenger/pull/206?utm_source=github">Review in cubic</a>

### CODE REVIEW

File: src/platforms/discord/commands/dm.test.ts [hunk 1]
```diff
@@ -125,18 +132,19 @@ describe('dm commands', () => {
...
       const consoleSpy = mock(() => {})
       const originalLog = console.log
       console.log = consoleSpy
 
-      await createAction('456', { pretty: false })
-
-      console.log = originalLog
-      process.exit = originalExit
+      try {
+        await expect(createAction('456', { pretty: false })).rejects.toThrow(ProcessExit)
```
[the remark this answers is not in the document]
Comment (devxoul) [reply src/platforms/discord/commands/dm.test.ts:144]: Good catch. Fixed in 6207ca6 — the per-test `exitSpy` is now restored explicitly via `exitSpy.mockRestore()` in each `finally` block, matching the file's existing spy-cleanup convention. (It was already covered by the global `afterEach(mock.restore())` preload, but explicit restoration is clearer and removes the implicit dependency.)

File: src/platforms/discord/commands/dm.test.ts [hunk 2]
```diff
@@ -86,18 +92,19 @@ describe('dm commands', () => {
...
       const consoleSpy = mock(() => {})
       const originalLog = console.log
       console.log = consoleSpy
 
-      await listAction({ pretty: false })
-
-      console.log = originalLog
-      process.exit = originalExit
+      try {
+        await expect(listAction({ pretty: false })).rejects.toThrow(ProcessExit)
```
[the remark this answers is not in the document]
Comment (devxoul) [reply src/platforms/discord/commands/dm.test.ts:104]: Good catch. Fixed in 6207ca6 — the per-test `exitSpy` is now restored explicitly via `exitSpy.mockRestore()` in each `finally` block, matching the file's existing spy-cleanup convention. (It was already covered by the global `afterEach(mock.restore())` preload, but explicit restoration is clearer and removes the implicit dependency.)

File: src/platforms/discord/commands/reaction.test.ts [hunk 3]
```diff
@@ -114,21 +120,19 @@ it('add: handles missing token gracefully', async () => {
 
   const consoleSpy = mock((_msg: string) => {})
   const originalLog = console.log
-  const originalExit = process.exit
-  let _exitCode = 0
-  process.exit = mock((code: number) => {
-    _exitCode = code
-  }) as any
+  const exitSpy = spyOn(process, 'exit').mockImplementation((code?: string | number | null) => {
```
[the remark this answers is not in the document]
Comment (devxoul) [reply src/platforms/discord/commands/reaction.test.ts:123]: Good catch. Fixed in 6207ca6 — the per-test `exitSpy` is now restored explicitly via `exitSpy.mockRestore()` in each `finally` block, matching the file's existing spy-cleanup convention. (It was already covered by the global `afterEach(mock.restore())` preload, but explicit restoration is clearer and removes the implicit dependency.)
