### PR TITLE
fix: green up main CI (test mock pollution + nondeterministic profile order)

### PR DESCRIPTION
**Pull request by devxoul**
## Summary

CI on `main` was failing (run #26444855239). There were **two independent root causes**, both of which only surface in the full `bun test src/` run — every affected test passes in isolation, which is the classic signature of cross-file pollution + filesystem-order dependence.

## Root cause 1 — Bun mock pollution across test files

The Webex command tests (`message`, `space`, `snapshot`, `member`) used `mock.module('../client', ...)`, and `whoami` used a module-export constructor spy `spyOn(clientModule, 'WebexClient')`.

Bun's `mock.module` is **process-global and persistent** — it is not undone between files. Once any of these files ran, every later file that imported `../client` got the mocked `WebexClient` (which lacks a real `testAuth`/`login` on its prototype). On the CI runner's file ordering this broke:

- `webex auth ... testAuth is not a function`
- `webex whoami exits with code 1 when not authenticated` → `No Webex credentials found.`
- `discord dm listAction/createAction handles authentication error` → `Token is required`
- `discord reaction add: handles missing token gracefully` → `Token is required`

**Fix:** replace the global module mocks with restorable `spyOn(WebexClient.prototype, ...)` spies (tracked and `mockRestore()`d in `afterEach`), and drop the global `@/shared/utils/error-handler` module mock in favor of a `process.exit` spy. Each file now cleans up fully after itself, so it can no longer poison sibling files.

## Root cause 2 — nondeterministic browser-profile ordering

`discoverBrowserProfileDirs` pushed numbered profiles in raw `readdirSync` order, which is unsorted on Linux. CI produced `[Default, Profile 2, Profile 1]`, failing the order-sensitive assertion (passes on macOS where readdir happens to be sorted).

**Fix:** sort numbered profiles by their parsed numeric index (so `Profile 2` < `Profile 10`), keeping `Default` first. Applied inside `discoverBrowserProfileDirs` so all callers benefit.

## Verification

- `bun typecheck` — clean
- `bun lint` — 0 warnings, 0 errors
- `bun run format:check` — changed files correctly formatted
- Reproductions confirmed fixed in both file orderings; all webex commands together; webex → discord cross-check
- Full `bun test src/` — all previously-failing webex/discord/browsers tests now pass

> Note: a handful of `slack TokenExtractor` tests fail locally because they read real Slack/browser data on the dev machine; they are pre-existing (identical on `main`), environment-specific, and pass on CI's clean runner. They are untouched by this PR.

---
## Summary by cubic
Fix CI failures on main by removing test mock pollution (Webex + WhatsApp) and making browser profile discovery deterministic. The full `bun test src/` run now passes consistently on CI.

- **Bug Fixes**
  - Webex tests: replaced global module mocks with restorable `spyOn(WebexClient.prototype, ...)`; mocked `process.exit`; added per-file cleanup to prevent cross-file leaks.
  - WhatsApp: removed global error-handler test mock; tests now spy on `process.exit`; updated `src/platforms/whatsapp/commands/auth.ts` to return `process.exit(...)` for clean test control flow.
  - Browser profiles: `discoverBrowserProfileDirs` now sorts numbered profiles by numeric index, keeping `Default` first, to avoid filesystem-order flakiness.
  - Docs: SKILL.md/docs not updated (no user-facing changes).

<sup>Written for commit f1f846b3936e344e1f31c3801e267ff44e24b0e1. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/agent-messenger/agent-messenger/pull/207?utm_source=github">Review in cubic</a>

### CODE REVIEW

**Comment by devxoul** [comment]
Closing in favor of #206, which fixes the same CI failure (cross-file Bun `mock.module` pollution + nondeterministic `readdirSync` order). #206 is authored by the repo owner, covers the Instagram polluter this PR missed, and adds a global `src/test-setup.ts` preload running `mock.restore()` after every test — a stronger safety net against any future mock leak.
